#!/usr/bin/env bash
set -x

export RAILS_ENV=test

function install_bundler() {
  gem install bundler -v 1.3.5 --conservative
}

function install_gems() {
  bundle check || bundle
}

function prepare_database() {
  bundle exec rake db:drop db:create db:migrate --trace
}

function prepare_and_run() {
  install_bundler &&
  install_gems &&
  prepare_database &&
  bundle exec rspec $(echo $RUN_LIST | tr ',' ' ')
}

prepare_and_run
success=$?
exit $success